version:  '3'
services:
  mysql:
    image: mysql
    ports:
     - 3306:3306
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 01224659503
     
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: food-app-server
    ports: 
      - 3010:3010
    depends_on:
      - mysql
    stdin_open: true
    tty: true
